# Generated by Django 4.2.14 on 2024-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Signup", "0002_alter_signup_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="pic",
            field=models.ImageField(default="", upload_to="upload/"),
        ),
    ]
